# Generated by Django 5.1.7 on 2025-05-14 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipsAuth', '0005_userrole_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_contracts', models.BooleanField(default=False, verbose_name='View Contracts')),
                ('can_create_contracts', models.BooleanField(default=False, verbose_name='Create Contracts')),
                ('can_edit_contracts', models.BooleanField(default=False, verbose_name='Edit Contracts')),
                ('can_delete_contracts', models.BooleanField(default=False, verbose_name='Delete Contracts')),
                ('can_approve_contracts', models.BooleanField(default=False, verbose_name='Approve Contracts')),
                ('can_view_invoices', models.BooleanField(default=False, verbose_name='View Invoices')),
                ('can_create_invoices', models.BooleanField(default=False, verbose_name='Create Invoices')),
                ('can_edit_invoices', models.BooleanField(default=False, verbose_name='Edit Invoices')),
                ('can_delete_invoices', models.BooleanField(default=False, verbose_name='Delete Invoices')),
                ('can_approve_invoices', models.BooleanField(default=False, verbose_name='Approve Invoices')),
                ('can_view_vessels', models.BooleanField(default=False, verbose_name='View Vessels')),
                ('can_create_vessels', models.BooleanField(default=False, verbose_name='Create Vessels')),
                ('can_edit_vessels', models.BooleanField(default=False, verbose_name='Edit Vessels')),
                ('can_delete_vessels', models.BooleanField(default=False, verbose_name='Delete Vessels')),
                ('can_view_ports', models.BooleanField(default=False, verbose_name='View Ports')),
                ('can_create_ports', models.BooleanField(default=False, verbose_name='Create Ports')),
                ('can_edit_ports', models.BooleanField(default=False, verbose_name='Edit Ports')),
                ('can_delete_ports', models.BooleanField(default=False, verbose_name='Delete Ports')),
                ('can_view_crew', models.BooleanField(default=False, verbose_name='View Crew')),
                ('can_create_crew', models.BooleanField(default=False, verbose_name='Create Crew')),
                ('can_edit_crew', models.BooleanField(default=False, verbose_name='Edit Crew')),
                ('can_delete_crew', models.BooleanField(default=False, verbose_name='Delete Crew')),
                ('can_view_cargo', models.BooleanField(default=False, verbose_name='View Cargo')),
                ('can_create_cargo', models.BooleanField(default=False, verbose_name='Create Cargo')),
                ('can_edit_cargo', models.BooleanField(default=False, verbose_name='Edit Cargo')),
                ('can_delete_cargo', models.BooleanField(default=False, verbose_name='Delete Cargo')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='View Reports')),
                ('can_generate_reports', models.BooleanField(default=False, verbose_name='Generate Reports')),
                ('can_export_reports', models.BooleanField(default=False, verbose_name='Export Reports')),
                ('can_view_users', models.BooleanField(default=False, verbose_name='View Users')),
                ('can_create_users', models.BooleanField(default=False, verbose_name='Create Users')),
                ('can_edit_users', models.BooleanField(default=False, verbose_name='Edit Users')),
                ('can_delete_users', models.BooleanField(default=False, verbose_name='Delete Users')),
                ('can_view_settings', models.BooleanField(default=False, verbose_name='View Settings')),
                ('can_edit_settings', models.BooleanField(default=False, verbose_name='Edit Settings')),
                ('can_view_audit_logs', models.BooleanField(default=False, verbose_name='View Audit Logs')),
                ('can_view_documents', models.BooleanField(default=False, verbose_name='View Documents')),
                ('can_upload_documents', models.BooleanField(default=False, verbose_name='Upload Documents')),
                ('can_delete_documents', models.BooleanField(default=False, verbose_name='Delete Documents')),
                ('can_view_maintenance', models.BooleanField(default=False, verbose_name='View Maintenance')),
                ('can_create_maintenance', models.BooleanField(default=False, verbose_name='Create Maintenance')),
                ('can_edit_maintenance', models.BooleanField(default=False, verbose_name='Edit Maintenance')),
                ('can_delete_maintenance', models.BooleanField(default=False, verbose_name='Delete Maintenance')),
                ('can_view_billing', models.BooleanField(default=False, verbose_name='View Billing')),
                ('can_create_billing', models.BooleanField(default=False, verbose_name='Create Billing')),
                ('can_edit_billing', models.BooleanField(default=False, verbose_name='Edit Billing')),
                ('can_delete_billing', models.BooleanField(default=False, verbose_name='Delete Billing')),
                ('can_view_compliance', models.BooleanField(default=False, verbose_name='View Compliance')),
                ('can_edit_compliance', models.BooleanField(default=False, verbose_name='Edit Compliance')),
                ('can_view_risks', models.BooleanField(default=False, verbose_name='View Risks')),
                ('can_create_risks', models.BooleanField(default=False, verbose_name='Create Risks')),
                ('can_edit_risks', models.BooleanField(default=False, verbose_name='Edit Risks')),
                ('can_delete_risks', models.BooleanField(default=False, verbose_name='Delete Risks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permissions',
                'verbose_name_plural': 'User Permissions',
            },
        ),
    ]
