# Generated by Django 5.1.7 on 2025-05-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipsAuth', '0006_userpermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('operations_manager', 'Operations Manager'), ('finance_officer', 'Finance Officer'), ('operations_staff', 'Operations Staff'), ('viewer', 'Viewer'), ('support_staff', 'Support Staff')], max_length=50),
        ),
    ]
