# Generated by Django 5.1.7 on 2025-05-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipsAuth', '0008_useraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
