# Generated by Django 5.1.7 on 2025-03-15 08:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=200)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ar_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('en_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('en_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charter_party_dated', models.DateTimeField(default=django.utils.timezone.now)),
                ('charterer', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(blank=True, max_length=150, null=True)),
                ('charter_party_form', models.CharField(blank=True, max_length=150, null=True)),
                ('vessel', models.CharField(blank=True, max_length=150, null=True)),
                ('charter_party_speed', models.CharField(blank=True, max_length=150, null=True)),
                ('last_three_cargoes', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.CharField(blank=True, max_length=150, null=True)),
                ('heating', models.CharField(blank=True, max_length=150, null=True)),
                ('load_port', models.CharField(blank=True, max_length=150, null=True)),
                ('laycan', models.CharField(blank=True, max_length=150, null=True)),
                ('discharge_port', models.CharField(blank=True, max_length=150, null=True)),
                ('freight', models.CharField(blank=True, max_length=150, null=True)),
                ('demurrage', models.CharField(blank=True, max_length=150, null=True)),
                ('laytime', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_to', models.CharField(blank=True, max_length=150, null=True)),
                ('brokers', models.CharField(blank=True, max_length=150, null=True)),
                ('commission', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.IntegerField(blank=True, default=0, null=True)),
                ('contract_start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('contract_end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_name', models.CharField(max_length=250, unique=True)),
                ('en_name', models.CharField(max_length=250, unique=True)),
                ('power', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.FloatField(blank=True, default=0.0, null=True)),
                ('price_usd_in_word', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('aed_price_in_word', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('aed_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_obj', to='ShipOps.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShipOps.occupation')),
                ('user_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('rendered_name', models.CharField(max_length=255)),
                ('has_submenu', models.BooleanField(default=False)),
                ('is_nav_item', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='ShipOps.systempages')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipOps.occupation')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShipOps.systempages')),
            ],
        ),
    ]
