# Generated by Django 5.1.7 on 2025-03-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='page',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_obj',
        ),
        migrations.RemoveField(
            model_name='systempages',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SystemPages',
        ),
    ]
