# Generated by Django 5.1.7 on 2025-04-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0006_remove_userprofile_role_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Overdue'), (3, 'Cancelled')], default=0, help_text='Current status of the invoice'),
        ),
    ]
