# Generated by Django 5.1.7 on 2025-04-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0007_invoice_due_date_invoice_notes_invoice_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imo_number', models.CharField(max_length=20, unique=True, verbose_name='IMO Number')),
                ('vessel_type', models.CharField(max_length=50)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, max_length=50)),
                ('gross_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_overall', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Length Overall (m)')),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('draft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('maintenance', 'Under Maintenance'), ('repair', 'Under Repair'), ('docked', 'Docked'), ('unavailable', 'Unavailable')], default='operational', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vessel',
                'verbose_name_plural': 'Vessels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VesselDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration Certificate'), ('insurance', 'Insurance'), ('classification', 'Classification Certificate'), ('safety', 'Safety Certificate'), ('inspection', 'Inspection Report'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='vessel_documents/')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ShipOps.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='VesselMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='ShipOps.vessel')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
