# Generated by Django 5.1.4 on 2025-04-26 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0009_analyticslog_dashboard_reporttemplate_savedreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('contract', 'Contract Report'), ('invoice', 'Invoice Report'), ('vessel', 'Vessel Report'), ('financial', 'Financial Summary'), ('status', 'Status Overview')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_filters', models.JSONField(default=dict)),
                ('show_chart', models.BooleanField(default=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('doughnut', 'Doughnut Chart')], default='bar', max_length=20)),
                ('generator_function', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Static Report',
                'verbose_name_plural': 'Static Reports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('applied_filters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('chart_data', models.JSONField(blank=True, default=dict, null=True)),
                ('export_file', models.FileField(blank=True, null=True, upload_to='report_exports/')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ShipOps.staticreport')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'ordering': ['-executed_at'],
            },
        ),
    ]
