# Generated by Django 5.1.7 on 2025-04-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0010_staticreport_reportexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='reportexecution',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='template',
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AnalyticsLog',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='ReportExecution',
        ),
        migrations.DeleteModel(
            name='StaticReport',
        ),
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
        migrations.DeleteModel(
            name='SavedReport',
        ),
    ]
