# Generated by Django 5.1.7 on 2025-05-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0013_useraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAction',
        ),
    ]
