# Generated by Django 5.1.7 on 2025-05-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShipOps', '0016_contract_actual_discharge_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('vessel', 'Vessel'), ('maintenance', 'Maintenance'), ('document', 'Document'), ('deadline', 'Deadline'), ('system', 'System'), ('alert', 'Alert')], max_length=20)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='ShipOps_not_user_id_9f0b36_idx'), models.Index(fields=['notification_type'], name='ShipOps_not_notific_cd01c4_idx'), models.Index(fields=['created_at'], name='ShipOps_not_created_b8d576_idx')],
            },
        ),
    ]
